name: Test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

env:
  CI: "true"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  sdk:
    name: SDK
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.20", "1.21", "1.22", "1.23"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Lint
        run: make lint

      - name: Test
        run: make test

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: false

      - name: GolangCI
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62.2
